spring.application.name=docify-backend

# =========================================================
# DATABASE - LOCAL DEVELOPMENT
# =========================================================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/docify}
spring.datasource.username=${DB_USERNAME:docify}
spring.datasource.password=${DB_PASSWORD:docify_dev_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.open-in-view=false


# =========================================================
# SERVER
# =========================================================

server.port=${SERVER_PORT:8080}


# =========================================================
# ACTUATOR
# =========================================================

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


# =========================================================
# JWT
# =========================================================

jwt.secret=${JWT_SECRET:DocifyLocalDevelopmentSecret_2026_ChangeBeforeProduction_123456789}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}


# =========================================================
# FILE STORAGE
# =========================================================

file.storage.documents=storage/documents

# local = local filesystem
# supabase = Supabase Storage
app.storage.mode=${APP_STORAGE_MODE:local}


# =========================================================
# SUPABASE STORAGE
# =========================================================

supabase.url=${SUPABASE_URL:}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY:}
supabase.storage.bucket=${SUPABASE_STORAGE_BUCKET:docify-documents}


# =========================================================
# GOOGLE GEMINI
# =========================================================

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.5-flash

spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.text.model=gemini-embedding-001
spring.ai.google.genai.embedding.text.task-type=RETRIEVAL_DOCUMENT
spring.ai.google.genai.embedding.text.dimensions=768


# =========================================================
# PGVECTOR
# =========================================================

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.table-name=vector_store


# =========================================================
# MULTIPART UPLOAD LIMITS
# =========================================================

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=21MB